# Generated by Django 5.1.6 on 2026-06-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_buildtask_error_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='buildtask',
            new_name='brain_build_task_id_211ba1_idx',
            old_name='brain_buildt_task_id_7c6ad0_idx',
        ),
        migrations.RenameIndex(
            model_name='buildtask',
            new_name='brain_build_project_e7ab9e_idx',
            old_name='brain_buildt_project_3f8c64_idx',
        ),
        migrations.RenameIndex(
            model_name='buildtask',
            new_name='brain_build_status_1f9e7f_idx',
            old_name='brain_buildt_status_3b1bc9_idx',
        ),
        migrations.AddField(
            model_name='buildtask',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='buildtask',
            index=models.Index(fields=['user_id'], name='brain_build_user_id_1b54be_idx'),
        ),
    ]
