# Generated by Django 6.0.3 on 2026-03-13 17:28

import engines.auth_engine.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verification_expiry",
            field=models.DateTimeField(
                blank=True,
                default=engines.auth_engine.models.User.default_email_verification_expiry,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
